# MSP commands used by the runtime compatibility layer. Keep this module small:
# domains add commands when they gain a typed codec rather than importing the
# legacy configurator's entire mutable command surface.
MSP_CODES =
  API_VERSION: 1
  FC_VARIANT: 2
  FC_VERSION: 3
  BOARD_INFO: 4
  BUILD_INFO: 5
  NAME: 10
  SET_NAME: 11
  RX_MAP: 64
  STATUS: 101
  RAW_IMU: 102
  SERVO: 103
  RC: 105
  ATTITUDE: 108
  ANALOG: 110
  SERVO_CONFIGURATIONS: 120
  BATTERY_STATE: 130
  BATTERY_CONFIG: 32
  SET_BATTERY_CONFIG: 33
  CURRENT_METER_CONFIG: 40
  SET_CURRENT_METER_CONFIG: 41
  ADJUSTMENT_RANGES: 52
  SET_ADJUSTMENT_RANGE: 53
  VOLTAGE_METER_CONFIG: 56
  SET_VOLTAGE_METER_CONFIG: 57
  SENSOR_CONFIG: 96
  SET_SENSOR_CONFIG: 97
  SENSOR_ALIGNMENT: 126
  SET_SENSOR_ALIGNMENT: 220
  ACC_CALIBRATION: 205
  # 206 is both SET_ONDAS and MAG_CALIBRATION in the firmware — the
  # keys coexist here; consumers must never dispatch by 206 alone.
  MAG_CALIBRATION: 206
  STATUS_EX: 150
  UID: 160
  FILTER_CONFIG: 92
  PID_ADVANCED: 94
  RC_TUNING: 111
  PID: 112
  ONDAS: 114
  SET_PID_ADVANCED: 95
  SET_FILTER_CONFIG: 193
  SET_PID: 202
  SET_RC_TUNING: 204
  SET_ONDAS: 206
  SET_SERVO_CONFIGURATION: 212
  SERVO_MIX_RULES: 241
  SET_SERVO_MIX_RULE: 242
  ORNITHOPTER_GLIDE_DEGREE: 244
  CF_SERIAL_CONFIG: 54
  SET_CF_SERIAL_CONFIG: 55
  OSD_CONFIG: 84
  SET_OSD_CONFIG: 85
  VTX_CONFIG: 88
  SET_VTX_CONFIG: 89
  MODE_RANGES: 34
  SET_MODE_RANGE: 35
  FEATURE_CONFIG: 36
  SET_FEATURE_CONFIG: 37
  RX_CONFIG: 44
  SET_RX_CONFIG: 45
  ARMING_CONFIG: 61
  SET_ARMING_CONFIG: 62
  SET_RX_MAP: 65
  FAILSAFE_CONFIG: 75
  SET_FAILSAFE_CONFIG: 76
  RXFAIL_CONFIG: 77
  SET_RXFAIL_CONFIG: 78
  BOXNAMES: 116
  BOXIDS: 119
  BEEPER_CONFIG: 184
  SET_BEEPER_CONFIG: 185
  MODE_RANGES_EXTRA: 238
  EEPROM_WRITE: 250

export default MSP_CODES
export { MSP_CODES }